general = {
    name = "Pixie Audio";
    output_backend = "pa";
    port = 5000;
    drift_tolerance_in_seconds = 0.002;
    resync_threshold_in_seconds = 0.050;
    ignore_volume_control = "yes";
    volume_max_db = 0;
    volume_range_db = 60;
    interpolation = "soxr";
    log_verbosity = 1;
};

alsa = {
    output_device = "default";
    mixer_control_name = "Master";
    mixer_device = "default";
    output_rate = 44100;
    output_format = "S16";
    buffer_size = 98304;
    period_size = 24576;
};

sessioncontrol = {
    wait_for_completion = "no";
    allow_session_interruption = "yes";
    session_timeout = 20;
};

metadata = {
    enabled = "yes";
    include_cover_art = "yes";
    pipe_name = "/tmp/shairport-sync-metadata";
    pipe_timeout = 5000;
}; 